adjust test setup

diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -116,6 +116,7 @@ jobs:
   test:
     name: Test ${{ matrix.os.download_name }}-${{ matrix.python-version }}-${{ matrix.cloud-provider }}
     needs: build
+    timeout-minutes: 30
     runs-on: ${{ matrix.os.image_name }}
     strategy:
       fail-fast: false
@@ -169,7 +170,8 @@ jobs:
       - name: Install tox
         run: python -m pip install tox>=4
       - name: Run tests
-        run: python -m tox run -e `echo py${PYTHON_VERSION/\./}-{extras,unit,integ,pandas,sso}-ci | sed 's/ /,/g'`
+#        run: python -m tox run -e `echo py${PYTHON_VERSION/\./}-{extras,integ,pandas,sso}-ci | sed 's/ /,/g'`
+        run: python -m tox run -e `echo py${PYTHON_VERSION/\./}-{extras,integ}-ci | sed 's/ /,/g'`
         env:
           PYTHON_VERSION: ${{ matrix.python-version }}
           cloud_provider: ${{ matrix.cloud-provider }}
@@ -186,6 +188,9 @@ jobs:
           path: |
             .tox/.coverage
             .tox/coverage.xml
+
+      - name: Print LocalStack logs
+        run: localstack logs
 
 #  test-olddriver:
 #    name: Old Driver Test ${{ matrix.os.download_name }}-${{ matrix.python-version }}-${{ matrix.cloud-provider }}
@@ -258,143 +263,138 @@ jobs:
 #          PYTEST_ADDOPTS: --color=yes --tb=short
 #        shell: bash
 
-  test-fips:
-    name: Test FIPS linux-3.8-${{ matrix.cloud-provider }}
-    needs: build
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        cloud-provider: [aws]
-    steps:
-      - uses: actions/checkout@v4
-      - name: Setup parameters file
-        shell: bash
-        env:
-          PARAMETERS_SECRET: ${{ secrets.PARAMETERS_SECRET }}
-        run: |
-          gpg --quiet --batch --yes --decrypt --passphrase="$PARAMETERS_SECRET" \
-          .github/workflows/parameters/public/parameters_${{ matrix.cloud-provider }}.py.gpg > test/parameters.py
-      - name: Download wheel(s)
-        uses: actions/download-artifact@v4
-        with:
-          name: manylinux_x86_64_py3.8
-          path: dist
-      - name: Show wheels downloaded
-        run: ls -lh dist
-        shell: bash
-      - name: Run tests
-        run: ./ci/test_fips_docker.sh
-        env:
-          PYTHON_VERSION: 3.8
-          cloud_provider: ${{ matrix.cloud-provider }}
-          PYTEST_ADDOPTS: --color=yes --tb=short
-          TOX_PARALLEL_NO_SPINNER: 1
-        shell: bash
-      - uses: actions/upload-artifact@v4
-        with:
-          include-hidden-files: true
-          name: coverage_linux-fips-3.8-${{ matrix.cloud-provider }}
-          path: |
-            .coverage
-            coverage.xml
+#  test-fips:
+#    name: Test FIPS linux-3.8-${{ matrix.cloud-provider }}
+#    needs: build
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        cloud-provider: [aws]
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Setup parameters file
+#        shell: bash
+#        env:
+#          PARAMETERS_SECRET: ${{ secrets.PARAMETERS_SECRET }}
+#        run: |
+#          gpg --quiet --batch --yes --decrypt --passphrase="$PARAMETERS_SECRET" \
+#          .github/workflows/parameters/public/parameters_${{ matrix.cloud-provider }}.py.gpg > test/parameters.py
+#      - name: Download wheel(s)
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: manylinux_x86_64_py3.8
+#          path: dist
+#      - name: Show wheels downloaded
+#        run: ls -lh dist
+#        shell: bash
+#      - name: Run tests
+#        run: ./ci/test_fips_docker.sh
+#        env:
+#          PYTHON_VERSION: 3.8
+#          cloud_provider: ${{ matrix.cloud-provider }}
+#          PYTEST_ADDOPTS: --color=yes --tb=short
+#          TOX_PARALLEL_NO_SPINNER: 1
+#        shell: bash
+#      - uses: actions/upload-artifact@v3
+#        with:
+#          name: coverage_linux-fips-3.8-${{ matrix.cloud-provider }}
+#          path: |
+#            .coverage
+#            coverage.xml
 
-  test-lambda:
-    name: Test Lambda linux-${{ matrix.python-version }}-${{ matrix.cloud-provider }}
-    needs: build
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-#        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
-        python-version: ["3.11"]
-        cloud-provider: [aws]
-    steps:
-      - name: Set shortver
-        run: echo "shortver=${longver//./}" >> $GITHUB_ENV
-        env:
-          longver: ${{ matrix.python-version }}
-        shell: bash
-      - uses: actions/checkout@v4
-      - name: Setup parameters file
-        shell: bash
-        env:
-          PARAMETERS_SECRET: ${{ secrets.PARAMETERS_SECRET }}
-        run: |
-          gpg --quiet --batch --yes --decrypt --passphrase="$PARAMETERS_SECRET" \
-          .github/workflows/parameters/public/parameters_${{ matrix.cloud-provider }}.py.gpg > test/parameters.py
-      - name: Download wheel(s)
-        uses: actions/download-artifact@v4
-        with:
-          name: manylinux_x86_64_py${{ matrix.python-version }}
-          path: dist
-      - name: Show wheels downloaded
-        run: ls -lh dist
-        shell: bash
-      - name: Run tests
-        run: ./ci/test_lambda_docker.sh ${PYTHON_VERSION}
-        env:
-          PYTHON_VERSION: ${{ matrix.python-version }}
-          cloud_provider: ${{ matrix.cloud-provider }}
-          PYTEST_ADDOPTS: --color=yes --tb=short
-          TOX_PARALLEL_NO_SPINNER: 1
-        shell: bash
-      - uses: actions/upload-artifact@v4
-        with:
-          include-hidden-files: true
-          name: coverage_linux-lambda-${{ matrix.python-version }}-${{ matrix.cloud-provider }}
-          path: |
-            .coverage.py${{ env.shortver }}-lambda-ci
-            junit.py${{ env.shortver }}-lambda-ci-dev.xml
+#  test-lambda:
+#    name: Test Lambda linux-${{ matrix.python-version }}-${{ matrix.cloud-provider }}
+#    needs: build
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+##        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
+#        python-version: ["3.11"]
+#        cloud-provider: [aws]
+#    steps:
+#      - name: Set shortver
+#        run: echo "shortver=${longver//./}" >> $GITHUB_ENV
+#        env:
+#          longver: ${{ matrix.python-version }}
+#        shell: bash
+#      - uses: actions/checkout@v3
+#      - name: Setup parameters file
+#        shell: bash
+#        env:
+#          PARAMETERS_SECRET: ${{ secrets.PARAMETERS_SECRET }}
+#        run: |
+#          gpg --quiet --batch --yes --decrypt --passphrase="$PARAMETERS_SECRET" \
+#          .github/workflows/parameters/public/parameters_${{ matrix.cloud-provider }}.py.gpg > test/parameters.py
+#      - name: Download wheel(s)
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: manylinux_x86_64_py${{ matrix.python-version }}
+#          path: dist
+#      - name: Show wheels downloaded
+#        run: ls -lh dist
+#        shell: bash
+#      - name: Run tests
+#        run: ./ci/test_lambda_docker.sh ${PYTHON_VERSION}
+#        env:
+#          PYTHON_VERSION: ${{ matrix.python-version }}
+#          cloud_provider: ${{ matrix.cloud-provider }}
+#          PYTEST_ADDOPTS: --color=yes --tb=short
+#          TOX_PARALLEL_NO_SPINNER: 1
+#        shell: bash
+#      - uses: actions/upload-artifact@v3
+#        with:
+#          name: coverage_linux-lambda-${{ matrix.python-version }}-${{ matrix.cloud-provider }}
+#          path: |
+#            .coverage.py${{ env.shortver }}-lambda-ci
+#            junit.py${{ env.shortver }}-lambda-ci-dev.xml
 
-  combine-coverage:
-    if: ${{ success() || failure() }}
-    name: Combine coverage
-    needs: [lint, test, test-fips, test-lambda]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/download-artifact@v4
-        with:
-          path: artifacts
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.8'
-      - name: Display Python version
-        run: python -c "import sys; print(sys.version)"
-      - name: Upgrade setuptools and pip
-        run: python -m pip install -U setuptools pip wheel
-      - name: Install tox
-        run: python -m pip install tox>=4
-      - name: Collect all coverages to one dir
-        run: |
-          python -c '
-          from pathlib import Path
-          import shutil
-
-          src_dir = Path("artifacts")
-          dst_dir = Path(".") / ".tox"
-          dst_dir.mkdir()
-          for src_file in src_dir.glob("*/.coverage"):
-              dst_file = dst_dir / ".coverage.{}".format(src_file.parent.name[9:])
-              print("{} copy to {}".format(src_file, dst_file))
-              shutil.copy(str(src_file), str(dst_file))'
-      - name: Combine coverages
-        run: python -m tox run -e coverage
-      - name: Publish html coverage
-        uses: actions/upload-artifact@v4
-        with:
-          include-hidden-files: true
-          name: overall_cov_html
-          path: .tox/htmlcov
-      - name: Publish xml coverage
-        uses: actions/upload-artifact@v4
-        with:
-          include-hidden-files: true
-          name: overall_cov_xml
-          path: .tox/coverage.xml
-      - uses: codecov/codecov-action@v4
-        with:
-          files: .tox/coverage.xml
-          token: ${{ secrets.CODECOV_TOKEN }}
+#  combine-coverage:
+#    if: ${{ success() || failure() }}
+#    name: Combine coverage
+#    needs: [lint, test, test-fips, test-lambda]
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v3
+#      - uses: actions/download-artifact@v3
+#        with:
+#          path: artifacts
+#      - name: Set up Python
+#        uses: actions/setup-python@v4
+#        with:
+#          python-version: '3.8'
+#      - name: Display Python version
+#        run: python -c "import sys; print(sys.version)"
+#      - name: Upgrade setuptools and pip
+#        run: python -m pip install -U setuptools pip wheel
+#      - name: Install tox
+#        run: python -m pip install tox>=4
+#      - name: Collect all coverages to one dir
+#        run: |
+#          python -c '
+#          from pathlib import Path
+#          import shutil
+#
+#          src_dir = Path("artifacts")
+#          dst_dir = Path(".") / ".tox"
+#          dst_dir.mkdir()
+#          for src_file in src_dir.glob("*/.coverage"):
+#              dst_file = dst_dir / ".coverage.{}".format(src_file.parent.name[9:])
+#              print("{} copy to {}".format(src_file, dst_file))
+#              shutil.copy(str(src_file), str(dst_file))'
+#      - name: Combine coverages
+#        run: python -m tox run -e coverage
+##      - name: Publish html coverage
+##        uses: actions/upload-artifact@v3
+##        with:
+##          name: overall_cov_html
+##          path: .tox/htmlcov
+##      - name: Publish xml coverage
+##        uses: actions/upload-artifact@v3
+##        with:
+##          name: overall_cov_xml
+##          path: .tox/coverage.xml
+#      - uses: codecov/codecov-action@v3
+#        with:
+#          files: .tox/coverage.xml
